# Generated by Django 4.1.2 on 2022-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(1, 'new'), (2, 'reading'), (3, 'finished')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
