# Generated by Django 4.1.2 on 2022-10-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'new'), (2, 'reading'), (3, 'finished')], max_length=200)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_writing_year', models.DateField()),
                ('book_pages', models.IntegerField()),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.type')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
